@startuml
left to right direction

actor "Formateur" as fc
actor "Étudiant" as st

rectangle "Système de Gestion des Tâches" {
  usecase "Crud Tâche" as UC1
  usecase "Voir les Tâches Assignées" as UC2
  usecase "Mettre à Jour le Statut de la Tâche" as UC3
  usecase "Suivre la Progression de l'Étudiant" as UC4
  usecase "Filtrer les Tâches" as UC5
}

fc -- UC1 
st -- UC2 
' st -- UC5 
fc -- UC4 

UC5 <|-- UC2 : "extend"
UC2 <|-- UC3 : "extend"

@enduml
